# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer


Public code references from 5 repositories
github.com/m19cmjigen/dotfileslicense unknown
github.com/dextercdalogdog/hello-aws-ci-cdlicense unknown
github.com/marcossilvestrini/learning-lpic-2-202-450license MIT
github.com/mscnio/iac-spielwieselicense unknown
github.com/Mahagon/chocolatey-packageslicense MIT

```yaml
name: PowerShell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '43 13 * * 5'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Run PowerShell script
      run: pwsh -file script.ps1

    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
      with:
        path: .\
        recurse: true
        includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
        output: results.sarif

    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        name: PowerShell CI
```

Commit message:
```
Improve GitHub Actions workflow for PowerShell CI

- Clean up and fix duplicate content in the workflow file
- Set up a basic workflow to run PowerShell scripts on push and pull request events
- Use actions/checkout to check out the repository
- Use actions/setup-powershell to set up PowerShell environment
- Run a sample PowerShell script (script.ps1)
- Add PSScriptAnalyzer step for code analysis
- Upload SARIF results file
```


name: PSScriptAnalyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '43 13 * * 5'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true
          # Include your own basic security rules. Removing this option will run all the rules
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          name: PowerShell CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Run PowerShell script
      run: pwsh -file script.ps1
      [![.github/workflows/powershell.yml](https://github.com/blacktatty-multi/PowerShell/actions/workflows/powershell.yml/badge.svg?branch=main&event=create)](https://github.com/blacktatty-multi/PowerShell/actions/workflows/powershell.yml)
